modules:
  - galsim.des
  - galsim_extra
  - montara
  - numpy

pipeline:
  steps:
    - galsim_montara
    - coadd_nwgint
    - swarp
    - src_extractor
    - desdm_meds
    - pizza_cutter
    - metadetect
    - fitvd
    - delete_images
    - delete_sources

fitvd:
  conda_prefix: "$FITVD_ENV"
  n_jobs: 128
  det_band: "r"
  bands: ["g", "r", "i", "z"]

galsim_montara: {}

delete_images:
  delete_coadd: True
  delete_se: True
  delete_se_nwgint: True
  delete_seg: True
  save_tilenames: [DES0131-2458]

delete_sources:
  save_tilenames: [DES0131-2458]

swarp:
  coadd_bands: ["r", "i", "z"]

src_extractor: {}

coadd_nwgint:
  n_jobs: 128
  run_on_inputs: False

desdm_meds:
  n_jobs: 128
  use_nwgint: False

pizza_cutter:
  n_jobs: 32  # more jobs leads to OOM errors
  use_nwgint: False

metadetect:
  n_jobs: 128  # don't hyperthread

eval_variables:
  sstar_mag_col: &star_mag_col
    type: FormattedStr
    format: "%smag"
    items:
    - "$band"
  sgal_mag_col: &gal_mag_col
    type: FormattedStr
    format: "mag_%s_red_sim"
    items:
    - "$band"
  sz_col: &z_col "photoz"
  ftruth_g:
    type: List
    items:
    - 0.
    - '$float((@gal.ellip).g)'
    index: '@current_obj_type_index'
  ftruth_beta:
    type: List
    items:
    - 0.
    - '$float((@gal.ellip).beta.rad)'
    index: '@current_obj_type_index'
  ftruth_rotate:
    type: List
    items:
    - 0.
    - '$float((@gal.rotate).rad)'
    index: '@current_obj_type_index'
  seastlake_seed: null

input:
  desgal:
    file_name:
        type: FormattedStr
        format: /dvs_ro/cfs/cdirs/desbalro/cosmos_simcat/cosmos_simcat_v7_%s_seed%s.fits
        items:
        - "@output.tilename"
        - "$eastlake_seed"
    cuts:
        x_sim: [250, 9750]
        y_sim: [250, 9750]
        mag_i_red_sim: [15., 25.4]
        bdf_hlr: [0, 5]
        isgal: [1]
        mask_flags: [0]
  desstar:
    file_name:
        type: FormattedStr
        format: /dvs_ro/cfs/cdirs/desbalro/starsim/catalogs/merged_y6/%s.fits
        items:
        - "@output.tilename"
    mag_i_max: 25.
    mag_i_col: imag
  des_piff:
    file_name: "$piff_path"

image:
  type: WideScattered
  border: 15

  # The number of objects across the full focal plane.
  nobjects:
    type: MixedNObjects
    use_all_gals: True
    use_all_stars: True

  #could read this from the image headers, but let's set them explicitly for now
  xsize: 2048
  ysize: 4096

  world_pos:
    type: RADec
    ra:
      type: Degrees
      theta:
        type: Eval
        str: "ra_star if object_type_list[@obj_num-start_obj_num]=='star' else ra_gal"
        fra_gal: { type: DESGalValue, col: "ra_sim" }
        fra_star: { type: DESStarValue, col: "ra" }
    dec:
      type: Degrees
      theta:
        type: Eval
        str: "dec_star if object_type_list[@obj_num-start_obj_num]=='star' else dec_gal"
        fdec_gal: { type: DESGalValue, col: "dec_sim" }
        fdec_star: { type: DESStarValue, col: "dec" }

psf:
  type: DES_Piff
  depixelize: false
  gi_color:
    type: Eval
    str: "mag_g_star - mag_i_star if object_type_list[@obj_num-start_obj_num]=='star' else mag_g_gal - mag_i_gal"
    fmag_g_gal: { type: DESGalValue, col: "mag_g_red_sim" }
    fmag_i_gal: { type: DESGalValue, col: "mag_i_red_sim" }
    fmag_g_star: { type: DESStarValue, col: "gmag" }
    fmag_i_star: { type: DESStarValue, col: "imag" }
  iz_color:
    type: Eval
    str: "mag_i_star - mag_z_star if object_type_list[@obj_num-start_obj_num]=='star' else mag_i_gal - mag_z_gal"
    fmag_i_gal: { type: DESGalValue, col: "mag_i_red_sim" }
    fmag_z_gal: { type: DESGalValue, col: "mag_z_red_sim" }
    fmag_i_star: { type: DESStarValue, col: "imag" }
    fmag_z_star: { type: DESStarValue, col: "zmag" }

#No knots
gal:
    type: Sum
    items:
        - type: Exponential
          half_light_radius: { type: DESGalValue, col: bdf_hlr }
          flux: { type: Eval, str: "1-fracdev", ffracdev: { type: DESGalValue, col: bdf_fracdev } }

        - type: DeVaucouleurs
          half_light_radius: '@gal.items.0.half_light_radius'
          flux: "$1-@gal.items.0.flux"

    ellip:
        type: GBeta
        g: { type: Eval, str: "np.sqrt(g1**2 + g2**2)", fg1: { type: DESGalValue, col: bdf_g1 }, fg2: { type: DESGalValue, col: bdf_g2 } }
        beta: { type: Random }

    rotate: {type: Random}

    flux:
        type: Eval
        str: "10**(0.4*(mag_zp-mag))"
        fmag: { type: DESGalValue, col: *gal_mag_col }

    gsparams:
        folding_threshold: 1.0e-4

star:
    type: Gaussian  # Basically a delta function.
    sigma: 1.e-6
    flux: 0

stamp:
  type: CoaddMixedScene
  objects:
    # obj_type is specified, so these numbers aren't used
    star: 1
    gal: 1
  obj_type: {type: Eval,
    str: "object_type_list[i]",
    ii: "$obj_num-start_obj_num"
  }
  draw_method: no_pixel
  shear_scene: {type: Eval,
    str: "False if object_type_list[@obj_num-start_obj_num]=='star' else True"
  }
  shear:
    type: G1G2_zslice
    zlow: 0.
    zhigh: 6.
    z: {type: Eval,
      str: "-1 if object_type_list[@obj_num-start_obj_num]=='star' else z_gal",
      fz_gal: { type: DESGalValue, col: "$z_col" }
    }
    g1_slice: 0.00
    g2_slice: 0.00
    g1_other: 0.00
    g2_other: 0.00
  gsparams:
    maximum_fft_size: 32768  # 4 x default=8192

output:
  type: DESTile
  tilename: DES0433-2332
  bands: ["g", "r", "i", "z"]
  desrun: "des-pizza-slices-y6"
  imsim_data: "$os.environ['IMSIM_DATA']"
  noise_mode: from_weight
  add_bkg: False
  grid_objects: False
  nproc: 64

  #Save weight and badpix extensions too
  badpixfromfits:
    hdu: 1
    mask_hdu: 2
    mask_file: "$orig_image_path"
  weight:
    hdu: 2

  truth:
    columns:
      num: obj_num
      half_light_radius:
          type: Eval
          str: "0.0 if @current_obj_type=='star' else hlr"
          fhlr: "@gal.items.0.half_light_radius"
      g1: "$(@stamp.shear).g1"
      g2: "$(@stamp.shear).g2"
      g: "$truth_g"
      beta: "$truth_beta"
      rotate: "$truth_rotate"
      obj_type: "@current_obj_type"
      obj_type_index: "@current_obj_type_index"
      band: "band"
      mag_zp: "$mag_zp"
      laigle_number:
          type: Eval
          str: "-1 if @current_obj_type=='star' else int(laigle_number)"
          flaigle_number: { type: DESGalValue, col: laigle_number }
      z:
          type: Eval
          str: "-1. if @current_obj_type=='star' else z_gal"
          fz_gal: { type: DESGalValue, col: "$z_col" }
