#!/bin/bash

#example: ./imsims_script_jobsub_tcmhds DES0152-4957 54 540 24 300 1 0.02 configs/fiducial-old.yaml plus

export TILENAME=$1
export NCORES=$2
export MEMGB=$3
export HOURS=$4
export DISK=$5
export SLEEP=$6
export SHEAR=$7
export CONFIG=$8
export RUN_NAME=$9

echo user is $USER
echo home is $HOME
echo tilename is $TILENAME NCORES is $NCORES MEMGB ${MEMGB}GB HOURS ${HOURS}h SCRATCH DISK ${DISK}G SLEEP ${SLEEP}s
echo using SHEAR $SHEAR
echo using CONFIG $CONFIG
echo using NAME $RUN_NAME
jobsub_submit -G des \
              -e TILENAME \
              -e NCORES \
              -e SHEAR \
              -e CONFIG \
              -e RUN_NAME \
              --memory ${MEMGB}GB \
              --cpu ${NCORES} \
              --expected-lifetime ${HOURS}h \
              --disk ${DISK}GB \
              --resource-provides="JobClass=DES" \
              --resource-provides=usage_model="DEDICATED,OPPORTUNISTIC" \
              -f dropbox://${HOME}/.desservices.ini \
              -f dropbox://${HOME}/.rsyncrc \
              --singularity-image /cvmfs/singularity.opensciencegrid.org/fermilab/fnal-wn-sl7:latest \
              -e GFAL_PLUGIN_DIR=/usr/lib64/gfal2-plugins \
              -e GFAL_CONFIG_DIR=/etc/gfal2.d \
              file://imsims_script.sh

echo sleeping for $SLEEP
sleep $SLEEP
