modules:
  - galsim.des
  - galsim_extra
  - montara
  - numpy

pipeline:
  steps: [galsim_montara, pizza_cutter, metadetect, delete_images, delete_sources]

galsim_montara: {}

delete_images:
  delete_coadd: True
  delete_se: True
  delete_se_nwgint: True
  delete_seg: True
  save_tilenames: [DES0131-2458]

delete_sources:
  save_tilenames: [DES0131-2458]

meds:
  cutout_types: ['image','weight','seg','bmask']
  add_psf_data: True
  use_joblib: True
  use_rejectlist: False

single_band_swarp: {}
swarp:
  coadd_bands: ['r', 'i', 'z']
src_extractor: {}
coadd_nwgint: {}
pizza_cutter:
  n_jobs: 32  # more jobs leads to OOM errors
metadetect:
  n_jobs: 128  # don't hyperthread

eval_variables:
  sstar_mag_col: &star_mag_col
    type: FormattedStr
    format: "%smag"
    items:
    - "$band"
  sgal_mag_col: &gal_mag_col
    type: FormattedStr
    format: "mag_%s_dered"
    items:
    - "$band"
  sz_col: &z_col "photoz"

input:
  # Use analytic galaxies with size and flux parameters that match the distribution seen
  # in the COSMOS galaxies.
  catalog_sampler:
    file_name: /dvs_ro/cfs/cdirs/des/y3-image-sims/input_cosmos_v4.fits
    cuts:
      mag_i: [15., 25.] #use only 15<mag_i<25. for now.
      isgal: [1,] #select galaxies only since we're simulating stars separately.
      mask_flags: [0,] #apply mask flags
      bdf_hlr: [0., 5.]
  desstar:
    file_name:
        type: FormattedStr
        format: /dvs_ro/cfs/projectdirs/des/atong/y6kp-shear/starsim/catalogs/merged_y6/%s.fits
        items:
        - "@output.tilename"
    mag_i_max: 25.
    mag_i_col: imag

image:
  type: WideScattered
  border: 15

  # The number of objects across the full focal plane.
  nobjects:
    type: MixedNObjects
    ngalaxies:
      type: RandomPoisson
      mean: "$170000 * (((@coadd_wcs).toWorld(galsim.PositionD(9750, 0)).ra.deg - (@coadd_wcs).toWorld(galsim.PositionD(250, 0)).ra.deg) * (math.cos((@coadd_wcs).toWorld(galsim.PositionD(0, 250)).dec.rad) - math.cos((@coadd_wcs).toWorld(galsim.PositionD(0, 9750)).dec.rad))) / ((ra_max_deg - ra_min_deg) * (math.cos(math.radians(dec_max_deg)) - math.cos(math.radians(dec_min_deg))))"
    use_all_stars: True

  #could read this from the image headers, but let's set them explicitly for now
  xsize: 2048
  ysize: 4096

  world_pos:
    type: RADec
    ra:
      type: Degrees
      theta:
        type: Eval
        str: "ra_star if object_type_list[@obj_num-start_obj_num]=='star' else ra_gal"
        # fra_gal: { type: Random, min: "$ra_min_deg", max: "$ra_max_deg" }
        fra_gal:
          type: Random
          min: "$(@coadd_wcs).toWorld(galsim.PositionD(250, 0)).ra.deg"
          max: "$(@coadd_wcs).toWorld(galsim.PositionD(9750, 0)).ra.deg"
        fra_star: { type: DESStarValue, col: "ra" }
    dec:
      type: Degrees
      theta:
        type: Eval
        str: "dec_star if object_type_list[@obj_num-start_obj_num]=='star' else math.degrees(dec_gal_radians)"
        fdec_gal_radians:
          type: RandomDistribution
          function: "math.cos(x)"  # Uniform on the sky means P(delta) ~ cos(delta)
          # x_min: "$math.radians(dec_min_deg)"
          # x_max: "$math.radians(dec_max_deg)"
          x_min: "$(@coadd_wcs).toWorld(galsim.PositionD(0, 250)).dec.rad"
          x_max: "$(@coadd_wcs).toWorld(galsim.PositionD(0, 9750)).dec.rad"
        fdec_star: { type: DESStarValue, col: "dec" }

psf:
  type: Gaussian
  fwhm: 0.9

gal:
  type: Exponential
  half_light_radius: 0.5
  flux: "$10**(0.4*(mag_zp-23.5))"

star:
  type: Gaussian
  sigma: 1.e-6
  flux: 0

stamp:
  type: CoaddMixedScene
  objects:
    # obj_type is specified, so these numbers aren't used
    star: 1
    gal: 1
  obj_type: {type: Eval,
    str: "object_type_list[i]",
    ii: "$obj_num-start_obj_num"
  }
  draw_method: auto
  shear_scene: {type: Eval,
    str: "False if object_type_list[@obj_num-start_obj_num]=='star' else True"
  }
  shear:
    type: G1G2
    g1: 0.00
    g2: -0.02
  gsparams:
    maximum_fft_size: 16384

output:
  type: DESTile
  tilename: DES0433-2332
  bands: ["g", "r", "i", "z"]
  desrun: "des-pizza-slices-y6"
  imsim_data: "$os.environ['IMSIM_DATA']"
  noise_mode: from_weight
  add_bkg: False
  grid_objects: False
  nproc: 128

  #Save weight and badpix extensions too
  badpixfromfits:
    hdu: 1
    mask_hdu: 2
    mask_file: "$orig_image_path"
  weight:
    hdu: 2

  truth:
    columns:
      num: obj_num
      g1: "$(@stamp.shear).g1"
      g2: "$(@stamp.shear).g2"
      band: "band"
      mag_zp: "$mag_zp"
